### PR TITLE
Dmenne BUG

### PR DESCRIPTION
**Pull request by dmenne**
- Add R test programs to rats, pump, seeds, surgical (1-4, Volume 1) examples of BUGS manual.
- Added ".stanified" versions of Stan-programs to better reflect recommened practices. 
  -- using vectorized if possible
  -- replace 1/sigmasquared contortions by sigma
  -- delete duplicate or non-required files
  -- somewhat narrower or wider (=default) priors
  -- test if program converges by running with default random init instead of the constant init.

To discuss: there is a warning to increment in old version "rats_vec_unit.stan". Result seem ok, and I do not understand what to do; I tend to remove the example, it is not very useful, but try to understand first.

### CODE REVIEW

**Comment by benlambertStan** [comment]
Hi,

I'm also going through the example models in BUGS. Is it worth me continuing on volume 2 so as not to duplicate the workload?

Best,

Ben

**Comment by dmenne** [comment]
Hi, Ben,

 

I do this for my own education, but then Bob asked me to submit a pull request.

 

It certainly would be good to coordinate. What have you done already? Dividing by the volume line seems ok, but I don’t mind trying other examples.

 

Dieter

 

Von: benlambertStan [mailto:notifications@github.com] 
Gesendet: Freitag, 7. August 2015 15:23
An: stan-dev/example-models <example-models@noreply.github.com>
Cc: Dieter Menne <dieter.menne@menne-biomed.de>
Betreff: Re: [example-models] Dmenne BUG (#29)

 

Hi,

I'm also going through the example models in BUGS. Is it worth me continuing on volume 2 so as not to duplicate the workload?

Best,

Ben

**Comment by benlambertStan** [comment]
Hi Dieter,

I've also gone through most of the examples you mention, as well as the dogs and beta blockers examples from volume 1. Will commit my models to the GitHub next week sometime. 

I'll start to look at volume 2 examples now.

Cheers,

Ben

**Comment by syclik** [comment]
@benlambertStan, I would suggest you put what you have on a public branch now rather than wait another week to do so. Since we have a little momentum, it would be great if you coordinated and compared models.

I'd be interested in what both of you are trying to do in terms of having models run. This is related to #26.

**Comment by syclik** [comment]
and thanks, @dmenne.

@benlambertStan, if you've already looked at this pull request and think everything is reasonable, either write that as a comment or feel free to merge into the branch. If you don't get to it, I'll do it soon.

**Comment by benlambertStan** [comment]
Yes, will do - it will be good to compare across both of our runs.

**Comment by bob-carpenter** [comment]
I'll second what Daniel said --- it's better to get things into
a branch and commit early and often.  You can create a GitHub issue to
coordinate work if you both want to keep working on it.

Thanks.

- Bob

P.S.  We're about to figure out how to add developer names to all the
files we create in all of our public repos to both clear up copyright
issues and assign credit (or "blame" as GitHub would call it!).

- Bob

**Comment by dmenne** [comment]
@syclik I see your point in #26: it would be good to have TravisCI run these examples as a testbed. It was not the priority for me, my own interest is in using these examples to get rid of BUG-habits. The examples are a bit too close to the BUGs version, which is fine for a starter. I am also not fluent in makefiles, using interactive mode most of the time

My suggestion: please modify one of our examples so it fits your requirements. Adding testthat or whatever? Then I could try to follow that path.

I also had considered to create the examples in Notebook format (http://rmarkdown.rstudio.com/r_notebook_format.html) so that comments could be inserted.

**Comment by dmenne** [comment]
@syclik As a separate point: the links to bug on top of each file are still incorrect. I wanted to correct these globally, but it would mean that all files, even the non-revised ones, will be changed and need to be merged. What's the recommended procedure to follow?

**Comment by bob-carpenter** [comment]
Pull request.  Merge early and often with the develop (or master)
in this case.

**Comment by syclik** [comment]
@dmenne, this looks great. I'll merge now.

I still don't know what we want to do for automatic running / testing. If you have ideas, comment on #26.

**Pull request merged**
