### PR TITLE
Fixes for issue 99, BPA examples

### PR DESCRIPTION
**Pull request by mikemeredith**
Changes to generated quantities in Stan models to use conditional (on
non-detection) values for psi or omega as discussed in Issue 99. Also
typo in Ch.07/chs_mnl.stan

### CODE REVIEW

**Comment by mikemeredith** [comment]
For the Ch.06 models, I checked against the JAGS output, and in fact both the old and new results are close to JAGS.
I wrote a script to check that all the models in the BDA directory would compile, and that threw up an error with` Ch.07/cjs_mnl.stan`, "n_occ_minus_1" not found, which seems clearly a typo for "n_occasions_minus_1"; reject that if not the case.

**Comment by ito4303** [comment]
> that threw up an error withCh.07/cjs_mnl.stan, "n_occ_minus_1" not found, which seems clearly a typo for "n_occasions_minus_1"; reject that if not the case.

This model was accidentally dropped from my checking script, and also should be fixed.

**Comment by bob-carpenter** [comment]
@ito4303  Should this be merged?  I just realized it's just been sitting here.

**Comment by ito4303** [comment]
Yes. Please.

**Pull request merged**
