### PR TITLE
revised to only use two mdivide_ calls

### PR DESCRIPTION
**Pull request by Sycor4x**
this should be more efficient since mdivide_ is expensive.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks.  I hope @rtrangucci or @betanalpha or @avehtari can review.  This one's making my head hurt from the linear algebra.

**Comment by Sycor4x** [comment]
Over the weekend I'll take a look at the other GP scripts and see if similar improvements may be made.

**Comment by avehtari** [comment]
A good catch. Yes, it's correct. For big n, Cholesky will still dominate, but there shouldn't be any downsides for this change. Do you want to add other changes to the same pull request or make a new one for those?

**Comment by Sycor4x** [comment]
Your point about the Cholesky factorization dominating the computational cost is well-taken.

Please merge this one. Once I make review of the other GP scripts, I'll make a new PR to group together any of my possible future efficiency improvements.

**Pull request merged**
