### PR TITLE
Changes to ARM/Ch.3/3.1_OnePredictor Models and R code

### PR DESCRIPTION
**Pull request by ericnovik**
Please, let me know if this is OK.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Sorry for taking so long --- I forgot there were pull requests still here.

Looks good to me.  But now there seems to be some kind of merge conflict.

**Comment by syclik** [comment]
@ericnovik, does your branch still exist?

**Comment by ericnovik** [comment]
Do we need it? I think this was merged.

**Comment by syclik** [comment]
It wasn't merged, but we can skip it. No harm if it's hard to find the branch.

**Comment by jgabry** [comment]
At one point I merged a PR from Eric into example-models, is this something
different?

**Comment by bob-carpenter** [comment]
@ericnovik Sorry that I completely forgot reviewing this whole repo.  Looks like there are conflicts now.  Do you want to clean this up or retract it?

**Comment by bob-carpenter** [comment]
I'm going to close this given that there hasn't been a response on cleaning up the conflicts.

**Pull request closed without merging**
