### PR TITLE
mle-params: Describe distinction between posterior mode and ML estimator

### PR DESCRIPTION
**Pull request by sdewaele**
Copyright by Stijn de Waele. I agree to license under BSD for the code, and CC-BY for the text.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Would you mind adding a note indicating who owns the copyright and agreeing to license under BSD for code and CC-BY for text?  Then I'll merge.

Thanks---forgot about this on the queue.  Got busy writing grant proposals after 2.14.

**Comment by sdewaele** [comment]
I adjusted my original comment to include the copyright note that you requested.

**Comment by bob-carpenter** [comment]
@sdewaele Thanks!

**Comment by sdewaele** [comment]
Just curious - do you have an indication when the new version will be released on the website?

**Comment by bob-carpenter** [comment]
Sorry --- forgot to generate a new version through knitr.  I'll go do that now. 

We need to figure out how to automate this process.

**Comment by bob-carpenter** [comment]
OK, the new version's up.  

I capitalized the title and added a "The" and also added an acknowledgement.  Thanks again.  

Thanks also for the reminder to put up the new version.

**Pull request merged**
