### PR TITLE
Master

### PR DESCRIPTION
**Pull request by danielcfurr**
Prepare several IRT case studies for web.

### CODE REVIEW

**Comment by danielcfurr** [comment]
Updated the 2PL tutorial to reflect changes I made to edstan. Fixed the misuse of rstan monitor() function throughout the case studies.

**Comment by danielcfurr** [comment]
Updated the 2PL tutorial to reflect changes I made to edstan. Fixed the misuse of rstan monitor() function throughout the case studies.

**Comment by bob-carpenter** [comment]
@danielcfurr  Is this still active?  Do you have permission to merge your own changes?

**Comment by danielcfurr** [comment]
Yes, it's still active. I do not have the permissions to merge it myself.
If you can set me up with that it would be great. I'd be happy to not have
to bug you with it.

**Comment by bob-carpenter** [comment]
I think I just gave you permission --- they keep tinkering with the interfaces.  Let me know if it doesn't work.

**Comment by danielcfurr** [comment]
Yes, this worked. Thank you, Bob.

**Pull request merged**
